# Generated by Django 5.2.8 on 2025-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritinerary',
            name='study_tour',
        ),
        migrations.AlterModelOptions(
            name='studytourbooking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AddField(
            model_name='studytourbooking',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytourbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('paid', '💰 Paid'), ('partial', '💳 Partial'), ('refunded', '🔄 Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studytourbooking',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('confirmed', '✅ Confirmed'), ('cancelled', '❌ Cancelled'), ('completed', '🎉 Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='DayActivity',
        ),
        migrations.DeleteModel(
            name='TourItinerary',
        ),
    ]
