# Generated by Django 5.2.9 on 2025-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_touritinerary_study_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('badge', models.CharField(blank=True, choices=[('', 'No Badge'), ('genius', 'Genius'), ('featured', 'Featured'), ('popular', 'Popular'), ('new', 'New')], max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=8.0, max_digits=3)),
                ('rating_text', models.CharField(choices=[('exceptional', 'Exceptional'), ('wonderful', 'Wonderful'), ('very_good', 'Very Good'), ('good', 'Good'), ('pleasant', 'Pleasant')], default='good', max_length=50)),
                ('reviews_count', models.IntegerField(default=0)),
                ('deal_tag', models.CharField(blank=True, help_text="e.g., 'Late Escape Deal', 'Early 2026 Deal'", max_length=100)),
                ('duration_nights', models.IntegerField(default=2)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
