# Generated by Django 5.2.9 on 2025-12-31 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_travelpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='deal_tag',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='duration_nights',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='rating_text',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='reviews_count',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='duration_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='group_size',
            field=models.IntegerField(default=20, help_text='Maximum group size'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key features, one per line'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Any special requests or notes')),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.travelpackage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bookings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
