# Generated by Django 5.2.9 on 2025-12-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactmessage'),
        ('accounts', '0004_remove_travelpackage_badge_and_more'),
    ]

    operations = [
    ]
