# Generated by Django 5.2.9 on 2025-12-31 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20260101_0352'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='created_by',
        ),
        migrations.CreateModel(
            name='CustomTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=200)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(help_text='Expected duration in days')),
                ('num_persons', models.IntegerField()),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('additional_details', models.TextField(blank=True, help_text='Any specific places you want to visit or other requirements')),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PackageBooking',
        ),
        migrations.DeleteModel(
            name='TravelPackage',
        ),
    ]
