# Generated by Django 5.2.9 on 2025-12-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots', '0003_packagebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebooking',
            name='student_notified',
            field=models.BooleanField(default=False),
        ),
    ]
