# Generated by Django 5.2.9 on 2025-12-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_spots', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='category',
            field=models.CharField(choices=[('study_tour', 'Study Tour'), ('cycling', 'Cycling'), ('university_program', 'University Program')], default='study_tour', max_length=50),
        ),
    ]
